# Sample travis
language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly


install:
  - gem install fpm --no-rdoc --no-ri # for packaging
  - gem install package_cloud --no-ri --no-rdoc # for deploying


after_success:
  - fpm -t deb -s dir -a all -n rustbyexample -v $(cargo pkgid| awk -F'#' {'print $2'}) target/debug/rustbyexample